// src/renderer/views/Home.jsx
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { QrScanner } from '@yudiel/react-qr-scanner';
import ApiService from '../../utils/api_service';

const Home = () => {
  const navigate = useNavigate();
  const [showQrScanner, setShowQrScanner] = useState(false);
  const [showUsageGuide, setShowUsageGuide] = useState(false);
  const [carWashState, setCarWashState] = useState(null);
  const isDevelopment = process.env.NODE_ENV === 'development';

  useEffect(() => {
    const unsubscribe = window.machineIPC.subscribeUpdates('0', (state) => {
      console.log('세차기 상태 업데이트:', state);
      setCarWashState(state);
    });

    return () => {
      if (unsubscribe) unsubscribe();
    };
  }, []);

  const startWash = () => {
    navigate('/products');
  };

  const checkReservation = () => {
    setShowQrScanner(true);
  };

  const closeQrScanner = () => {
    setShowQrScanner(false);
  };

  const toggleUsageGuide = () => {
    setShowUsageGuide(!showUsageGuide);
  };

  const onDecode = async (result) => {
    if (result) {
      try {
        const [qrIdx, qrCreatedAt, qrChecksum] = result.split('|');
        
        const reservationResponse = await ApiService.getReservation({
          qr_idx: qrIdx,
          qr_created_at: qrCreatedAt,
          qr_checksum: qrChecksum,
        });
        
        if (reservationResponse.item) {
          const updateResponse = await ApiService.updateReservationStatus(
            reservationResponse.item.idx,
            'COMPLETE',
            null
          );
          
          if (updateResponse.type === 'SUCCESS') {
            const controlResponse = await ApiService.controlCarWash('START');
            
            if (controlResponse.success) {
              alert('예약이 확인되었습니다. 세차를 시작합니다.');
            } else {
              alert('세차기 시작에 실패했습니다. 관리자에게 문의해주세요.');
            }
          } else {
            alert('예약 상태 업데이트에 실패했습니다. 다시 시도해주세요.');
          }
        } else {
          alert('유효하지 않은 QR 코드입니다.');
        }
        
        closeQrScanner();
      } catch (error) {
        console.error('예약 확인 중 오류가 발생했습니다:', error);
        alert('예약 확인 중 오류가 발생했습니다. 다시 시도해주세요.');
      }
    }
  };

  const isWashing = carWashState && carWashState.isWashing;

  return (
    <div className="flex-1 p-8 flex flex-col items-center justify-center">
      <div className="text-4xl font-bold text-green-500 mb-4">BOOSTER</div>
      <h1 className="text-2xl font-semibold text-center mb-8">
        안녕하세요. 고객님<br />씻자 진주점입니다.
      </h1>
      <div className="flex space-x-4 mb-8">
        <button
          onClick={startWash}
          className={`bg-gray-800 text-white px-6 py-4 rounded-2xl flex flex-col items-center transition duration-300 ${isWashing ? 'opacity-50 cursor-not-allowed' : 'hover:bg-gray-700'}`}
          disabled={isWashing}
        >
          <span>자동세차</span>
          <span>현장결제</span>
          <span className="mt-2 text-2xl">→</span>
        </button>
        <button
          onClick={checkReservation}
          className={`bg-gray-800 text-white px-6 py-4 rounded-2xl flex flex-col items-center transition duration-300 ${isWashing ? 'opacity-50 cursor-not-allowed' : 'hover:bg-gray-700'}`}
          disabled={isWashing}
        >
          <span>자동세차</span>
          <span>QR 확인</span>
          <span className="mt-2 bg-green-500 text-white rounded-full w-8 h-8 flex items-center justify-center">QR</span>
        </button>
      </div>
      <button onClick={toggleUsageGuide} className="text-green-500 underline mb-4">
        부스터 키오스크 사용 안내
      </button>

      {carWashState && (
        <div className="bg-gray-800 p-4 rounded-xl text-white mb-4">
          <h3 className="text-lg font-semibold mb-2">세차기 상태</h3>
          <p>상태: {carWashState.machineStatus === 'washing' ? '세차 중' : '대기 중'}</p>
          <p>현재 단계: {carWashState.currentStep || '없음'}</p>
          {carWashState.remainingTime !== undefined && (
            <>
              <p>남은 시간: {Math.floor(carWashState.remainingTime / 60)}분 {carWashState.remainingTime % 60}초</p>
              <p>진행률: {100 - carWashState.remainingPercent}%</p>
            </>
          )}
          <p>입력 상태: {carWashState.inputStatus}</p>
          <p>오류 상태: {carWashState.error ? '오류' : '정상'}</p>
        </div>
      )}

      {showQrScanner && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white p-8 rounded-lg max-w-md w-full text-black">
            <div className="flex justify-between items-center mb-4">
              <h2 className="text-2xl font-bold">QR 코드를 스캔해주세요</h2>
              <button onClick={closeQrScanner} className="text-gray-500 hover:text-gray-700">
                <span className="text-2xl">&times;</span>
              </button>
            </div>
            <p className="mb-4">예약 확인을 위해 QR 코드를 카메라에 보여주세요.</p>
            {isDevelopment ? (
              <QrScanner
                onDecode={onDecode}
                onError={(error) => console.log(error?.message)}
                className="w-full h-64"
              />
            ) : (
              <div className="bg-gray-200 w-full h-64 flex items-center justify-center">
                <p>카메라가 활성화되었습니다. QR 코드를 스캔해주세요.</p>
              </div>
            )}
          </div>
        </div>
      )}

      {showUsageGuide && (
        <div className="fixed inset-0 bg-black bg-opacity-80 flex items-center justify-center z-50">
          <div className="bg-gray-800 p-8 rounded-3xl max-w-2xl w-full text-white relative">
            <button onClick={toggleUsageGuide} className="absolute top-4 right-4 text-white">
              <span className="text-3xl">&times;</span>
            </button>
            <h2 className="text-2xl font-bold mb-6 text-center">부스터 키오스크 사용 안내</h2>
            <div className="space-y-6">
              <div className="flex items-start">
                <div className="bg-green-500 text-white rounded-full w-8 h-8 flex items-center justify-center mr-4 flex-shrink-0">1</div>
                <p>앱 예약, 구독은 '자동세차 QR확인' 버튼으로 현장에서 결제할 경우 '자동세차 현장결제' 버튼을 눌러주세요.</p>
              </div>
              <div className="flex items-start">
                <div className="bg-green-500 text-white rounded-full w-8 h-8 flex items-center justify-center mr-4 flex-shrink-0">2</div>
                <p>QR확인은 모니터 왼쪽 하단에 30cm 거리 안에서 스캔하고 세차를 진행해 주세요.</p>
              </div>
              <div className="flex items-start">
                <div className="bg-green-500 text-white rounded-full w-8 h-8 flex items-center justify-center mr-4 flex-shrink-0">3</div>
                <p>현장 결제는 원하는 상품을 누르고 전화번호 입력 후 모니터 오른쪽 하단 카드결제하고 세차를 진행해 주세요.</p>
              </div>
            </div>
            <div className="mt-8 bg-gray-700 p-4 rounded-xl">
              <h3 className="text-green-500 font-bold mb-2">이 시대 자동세차를 위한 구독요금제</h3>
              <p className="text-xl font-bold">요금은 <span className="text-green-500">더 낮게</span> 세차는 <span className="text-green-500">더 많이</span></p>
              <p className="text-xl font-bold"><span className="text-green-500">자동세차 구독</span></p>
              <p className="text-sm mt-2">앱에서 구독을 확인하세요.</p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default Home;

// src/renderer/views/Home.vue
<template>
  <div class="home">
    <div class="content">
      <div class="logo">BOOSTER</div>
      <h1>부스터 세차</h1>
      <p>최고의 세차 서비스를 경험해보세요</p>
      <div class="button-container">
        <button @click="startWash" class="main-button">세차 시작하기</button>
        <button @click="checkReservation" class="main-button">예약 확인</button>
      </div>
    </div>

    <!-- QR 코드 스캐너 모달 -->
    <div v-if="showQrScanner" class="qr-scanner-modal">
      <div class="qr-scanner-content">
        <button @click="closeQrScanner" class="close-button">
          <span class="close-icon">&#10005;</span>
        </button>
        <h2>QR 코드를 스캔해주세요</h2>
        <p class="scanner-instruction">예약 확인을 위해 QR 코드를 카메라에 보여주세요.</p>
        <qrcode-stream v-if="isDevelopment" @decode="onDecode" @init="onInit"></qrcode-stream>
        <div v-else class="qr-placeholder">
          <p>카메라가 활성화되었습니다. QR 코드를 스캔해주세요.</p>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { QrcodeStream } from 'vue-qrcode-reader'
import ApiService from '../../utils/api_service'

const router = useRouter()
const showQrScanner = ref(false)
const isDevelopment = process.env.NODE_ENV === 'development'

const startWash = () => {
  router.push('/products')
}

const checkReservation = () => {
  showQrScanner.value = true
}

const closeQrScanner = () => {
  showQrScanner.value = false
}

const onInit = async (promise) => {
  try {
    await promise
  } catch (error) {
    if (error.name === 'NotAllowedError') {
      console.error('카메라 접근 권한이 없습니다.')
    } else if (error.name === 'NotFoundError') {
      console.error('카메라를 찾을 수 없습니다.')
    } else if (error.name === 'NotSupportedError') {
      console.error('보안 컨텍스트에서 실행되지 않습니다.')
    } else if (error.name === 'NotReadableError') {
      console.error('카메라가 이미 사용 중입니다.')
    } else if (error.name === 'OverconstrainedError') {
      console.error('설치된 카메라가 없습니다.')
    } else if (error.name === 'StreamApiNotSupportedError') {
      console.error('브라우저가 필요한 API를 지원하지 않습니다.')
    } else {
      console.error('QR 코드 스캐너 초기화 중 오류가 발생했습니다:', error)
    }
  }
}

const onDecode = async (decodedString) => {
  try {
    const [qrIdx, qrCreatedAt, qrChecksum] = decodedString.split('|')
    
    const reservationResponse = await ApiService.getReservation({
      qr_idx: qrIdx,
      qr_created_at: qrCreatedAt,
      qr_checksum: qrChecksum
    })
    
    if (reservationResponse.item) {
      const updateResponse = await ApiService.updateReservationStatus(
        reservationResponse.item.idx,
        'COMPLETE',
        null
      )
      
      if (updateResponse.type === 'SUCCESS') {
        const controlResponse = await ApiService.controlCarWash('START')
        
        if (controlResponse.success) {
          alert('예약이 확인되었습니다. 세차를 시작합니다.')
        } else {
          alert('세차기 시작에 실패했습니다. 관리자에게 문의해주세요.')
        }
      } else {
        alert('예약 상태 업데이트에 실패했습니다. 다시 시도해주세요.')
      }
    } else {
      alert('유효하지 않은 QR 코드입니다.')
    }
    
    closeQrScanner()
  } catch (error) {
    console.error('예약 확인 중 오류가 발생했습니다:', error)
    alert('예약 확인 중 오류가 발생했습니다. 다시 시도해주세요.')
  }
}
</script>

<style scoped>
.home {
  height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
  background-color: #f0f0f0;
  color: #333;
  text-align: center;
}

.content {
  width: 80%;
  max-width: 600px;
}

.logo {
  font-size: 3rem;
  font-weight: bold;
  color: #4CAF50;
  margin-bottom: 1rem;
}

h1 {
  font-size: 2.5rem;
  margin-bottom: 1rem;
}

p {
  font-size: 1.2rem;
  margin-bottom: 2rem;
  color: #666;
}

.button-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 1rem;
}

.main-button {
  background-color: #4CAF50;
  border: none;
  color: white;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 1.2rem;
  margin: 4px 2px;
  cursor: pointer;
  border-radius: 5px;
  width: 100%;
  max-width: 300px;
  transition: background-color 0.3s;
}

.main-button:hover {
  background-color: #45a049;
}

.qr-scanner-modal {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.5);
  display: flex;
  justify-content: center;
  align-items: center;
}

.qr-scanner-content {
  background-color: white;
  padding: 20px;
  border-radius: 10px;
  text-align: center;
  position: relative;
  width: 80%;
  max-width: 400px;
}

.close-button {
  position: absolute;
  top: 10px;
  right: 10px;
  background: none;
  border: none;
  font-size: 20px;
  cursor: pointer;
  padding: 5px;
}

.close-icon {
  color: #333;
}

.scanner-instruction {
  margin-bottom: 20px;
  color: #666;
}

.qr-placeholder {
  border: 2px dashed #ccc;
  padding: 20px;
  margin-top: 20px;
  border-radius: 5px;
}
</style>
