// src/renderer/views/ProductList.jsx
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Product } from '../../models/models';
import ApiService from '../../utils/api_service';

const ServiceOption = ({ product, onSelect }) => (
  <div className="bg-gray-800 rounded-lg p-4 mb-4 flex justify-between items-center cursor-pointer" onClick={() => onSelect(product)}>
    <div>
      <h3 className="text-white font-bold">{product.name} ({product.duration}분)</h3>
      <p className="text-gray-400 text-sm">{product.description}</p>
    </div>
    <div className="flex items-center">
      <span className="text-green-400 font-bold mr-2">{product.price.toLocaleString()}원</span>
      <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
      </svg>
    </div>
  </div>
);

const ProductList = () => {
  const navigate = useNavigate();
  const [products, setProducts] = useState([]);
  const [error, setError] = useState(null);
  const [loading, setLoading] = useState(true);
  const [selectedProduct, setSelectedProduct] = useState(null);
  const [paymentStatus, setPaymentStatus] = useState(null);
  const [paymentMessage, setPaymentMessage] = useState('');
  const [countdown, setCountdown] = useState(5);

  useEffect(() => {
    const fetchProducts = async () => {
      try {
        const response = await ApiService.getProducts();
        setProducts(response.list.map(p => new Product(p.idx, p.name, p.description, p.price, p.duration, p.target_mode, p.payment_rf_only)));
      } catch (err) {
        console.error('상품 목록을 불러오는데 실패했습니다:', err);
        setError(err);
      } finally {
        setLoading(false);
      }
    };

    fetchProducts();
  }, []);

  const goBack = () => {
    navigate(-1);
  };

  const selectProduct = (product) => {
    setSelectedProduct(product);
    setPaymentStatus('waiting');
  };

  const processPayment = async () => {
    try {
      setPaymentStatus('processing');
      setPaymentMessage('결제 처리 중...');

      // 실제 환경에서는 여기에 카드 결제 시퀀스 로직을 구현합니다.
      // 개발 환경에서는 시뮬레이션된 결제 정보를 사용합니다.
      const paymentInfo = await simulatePayment();

      setPaymentMessage('예약 생성 중...');
      // 예약 요청
      const reservationResponse = await ApiService.createReservation({
        tel: '010-0000-0000', // TODO: 실제 사용자 전화번호 입력 받기
        product_idx: selectedProduct.idx,
        payment: paymentInfo,
        status: 'COMPLETE'
      });

      console.log('예약이 완료되었습니다:', reservationResponse);

      // 세차기 동작 시작
      try {
        const result = await window.machineIPC.startWash('0', selectedProduct.targetMode);
        console.log('세차기 제어 결과:', result);
        if (result.success) {
          setPaymentStatus('success');
        } else {
          throw new Error(result.error || '세차기 시작 실패');
        }
      } catch (error) {
        console.error('세차기 시작 중 오류 발생:', error);
        throw new Error('세차기를 시작할 수 없습니다. 관리자에게 문의해주세요.');
      }
    } catch (error) {
      console.error('결제 또는 예약 중 오류가 발생했습니다:', error);
      setPaymentStatus('failed');
      setPaymentMessage('결제 실패: ' + error.message);
    }
  };

  const simulatePayment = () => {
    return new Promise((resolve) => {
      setTimeout(() => {
        resolve({
          approval_number: 'SIM' + Math.random().toString(36).substr(2, 9),
          card_number: '**** **** **** ' + Math.floor(1000 + Math.random() * 9000),
          card_company_number: '01',
          type: 'CARD',
          amount: selectedProduct.price
        });
      }, 1000); // 1초 후 결제 완료 시뮬레이션
    });
  };

  useEffect(() => {
    let timer;
    if (paymentStatus === 'success') {
      timer = setInterval(() => {
        setCountdown((prevCount) => {
          if (prevCount === 1) {
            clearInterval(timer);
            setPaymentStatus(null);
            return 5;
          }
          return prevCount - 1;
        });
      }, 1000);
    }
    return () => clearInterval(timer);
  }, [paymentStatus]);

  const handleClose = () => {
    setPaymentStatus(null);
    setCountdown(5);
  };

  const handlePrintReceipt = () => {
    // 영수증 출력 로직
    handleClose();
  };

  const renderPaymentModal = () => {
    if (paymentStatus === 'waiting') {
      return (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-gray-800 p-8 rounded-3xl max-w-md w-full text-white">
            <h2 className="text-2xl font-bold mb-4">결제 대기 중</h2>
            <p>카드를 투입해 주세요.</p>
            <button onClick={processPayment} className="mt-4 bg-blue-500 text-white px-4 py-2 rounded">
              결제 시뮬레이션
            </button>
          </div>
        </div>
      );
    }
    if (paymentStatus === 'processing') {
      return (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-gray-800 p-8 rounded-3xl max-w-md w-full text-white">
            <h2 className="text-2xl font-bold mb-4">결제 처리 중</h2>
            <p>{paymentMessage}</p>
          </div>
        </div>
      );
    }
    if (paymentStatus === 'failed') {
      return (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-gray-800 p-8 rounded-3xl max-w-md w-full text-white">
            <h2 className="text-2xl font-bold mb-4">결제 실패</h2>
            <p>{paymentMessage}</p>
            <button onClick={() => setPaymentStatus(null)} className="mt-4 bg-red-500 text-white px-4 py-2 rounded">
              닫기
            </button>
          </div>
        </div>
      );
    }
    return null;
  };

  if (error) {
    return (
      <div className="text-white text-center p-4">
        <p>에러 발생: {error.message}</p>
      </div>
    );
  }

  if (loading) {
    return (
      <div className="text-white text-center p-4">
        <p>상품 목록을 불러오는 중...</p>
      </div>
    );
  }

  return (
    <div className="bg-black min-h-screen p-4">
      <div className="max-w-md mx-auto">
        <div className="relative mb-6">
          <img src="/path-to-your-image.jpg" alt="Car wash" className="w-full rounded-lg" />
          <button onClick={goBack} className="absolute top-4 left-4 bg-white rounded-full p-2">
            <svg className="w-6 h-6 text-black" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
            </svg>
          </button>
        </div>
        <h2 className="text-white text-2xl font-bold mb-6">상품 선택</h2>
        {products.map((product) => (
          <ServiceOption key={product.idx} product={product} onSelect={selectProduct} />
        ))}
      </div>
      {renderPaymentModal()}
      {paymentStatus === 'success' && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-gray-800 p-8 rounded-3xl max-w-md w-full text-white relative">
            <h2 className="text-2xl font-bold mb-4 text-center">결제가 완료되었습니다.</h2>
            <p className="mb-4 text-center">모니터 오른쪽 하단에 카드를 회수해 주세요.</p>
            <div className="flex justify-center mb-6">
              <img src="/path-to-success-icon.png" alt="Success Icon" className="w-24 h-24" />
            </div>
            <div className="flex justify-between mt-6">
              <button onClick={handleClose} className="bg-red-500 text-white px-6 py-2 rounded-full w-[48%]">
                닫기 ({countdown})
              </button>
              <button onClick={handlePrintReceipt} className="bg-green-500 text-white px-6 py-2 rounded-full w-[48%]">
                영수증 출력
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default ProductList;

// src/renderer/views/ProductList.vue
<template>
  <div class="product-list">
    <div class="header">
      <button @click="goBack" class="back-button">뒤로</button>
      <h2 class="title">세차 상품 선택</h2>
    </div>
    <div v-if="error" class="error-message">
      <p>에러 코드: {{ error.status }}</p>
      <p>{{ error.message }}</p>
    </div>
    <div v-else-if="loading" class="loading-message">
      <p>{{ loadingMessage }}</p>
    </div>
    <div v-else class="product-grid">
      <div v-for="product in products" :key="product.idx" class="product-item" @click="selectProduct(product)">
        <div class="product-content">
          <h3 class="product-name">{{ product.name }}</h3>
          <p class="product-description">{{ product.description }}</p>
          <p class="product-price">{{ product.price.toLocaleString() }}원</p>
          <p class="product-duration">소요 시간: {{ product.duration }}분</p>
        </div>
      </div>
    </div>

    <!-- 결제 팝업 -->
    <div v-if="showPaymentPopup" class="payment-popup">
      <div class="payment-content">
        <h2>결제</h2>
        <p>선택한 상품: {{ selectedProduct.name }}</p>
        <p>가격: {{ selectedProduct.price.toLocaleString() }}원</p>
        <p>{{ paymentMessage }}</p>
        <button v-if="isDevelopment" @click="processPayment" :disabled="loading">
          개발 모드: 결제 시뮬레이션
        </button>
        <button @click="cancelPayment" :disabled="loading">취소</button>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { Product } from '../../models/models'
import ApiService from '../../utils/api_service'

const router = useRouter()
const products = ref([])
const error = ref(null)
const loading = ref(true)
const loadingMessage = ref('상품 목록을 불러오는 중...')
const showPaymentPopup = ref(false)
const selectedProduct = ref(null)
const paymentMessage = ref('')
const isDevelopment = process.env.NODE_ENV === 'development'

onMounted(async () => {
  try {
    loadingMessage.value = '상품 목록을 불러오는 중...'
    const response = await ApiService.getProducts()
    products.value = response.list.map(p => new Product(p.idx, p.name, p.description, p.price, p.duration, p.target_mode, p.payment_rf_only))
  } catch (err) {
    console.error('상품 목록을 불러오는데 실패했습니다:', err)
    error.value = err
  } finally {
    loading.value = false
  }
})

const selectProduct = (product) => {
  selectedProduct.value = product
  showPaymentPopup.value = true
  if (!isDevelopment) {
    processPayment()
  }
}

const cancelPayment = () => {
  showPaymentPopup.value = false
  selectedProduct.value = null
  paymentMessage.value = ''
}

const processPayment = async () => {
  try {
    loading.value = true
    paymentMessage.value = '결제 처리 중...'

    // 실제 환경에서는 여기에 카드 결제 시퀀스 로직을 구현합니다.
    // 개발 환경에서는 시뮬레이션된 결제 정보를 사용합니다.
    const paymentInfo = await simulatePayment()

    paymentMessage.value = '예약 생성 중...'
    // 예약 요청
    const reservationResponse = await ApiService.createReservation({
      tel: '010-0000-0000', // TODO: 실제 사용자 전화번호 입력 받기
      product_idx: selectedProduct.value.idx,
      payment: paymentInfo,
      status: 'COMPLETE'
    })

    console.log('예약이 완료되었습니다:', reservationResponse)

    // 세차기 동작 시작
    try {
      const { ipcRenderer } = require('electron');
      await ipcRenderer.invoke('control-car-wash', {
        action: 'start',
        machineId: '0',
        mode: selectedProduct.value.targetMode // 선택된 제품의 target_mode를 세차 모드로 사용
      });
      console.log('세차기가 성공적으로 시작되었습니다.');
    } catch (error) {
      console.error('세차기 시작 중 오류 발생:', error);
      throw new Error('세차기를 시작할 수 없습니다. 관리자에게 문의해주세요.');
    } finally {
      loading.value = false
    }

    // 예약 완료 페이지로 이동
    router.push({ 
      name: 'reservation-complete', 
      params: { 
        reservationId: reservationResponse.item.idx,
        productName: selectedProduct.value.name,
        price: selectedProduct.value.price
      } 
    })
  } catch (error) {
    console.error('결제 또는 예약 중 오류가 발생했습니다:', error)
    paymentMessage.value = '결제 실패: ' + error.message
  } finally {
    loading.value = false
  }
}

const simulatePayment = () => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({
        approval_number: 'SIM' + Math.random().toString(36).substr(2, 9),
        card_number: '**** **** **** ' + Math.floor(1000 + Math.random() * 9000),
        card_company_number: '01',
        type: 'CARD',
        amount: selectedProduct.value.price
      })
    }, 1000) // 1초 후 결제 완료 시뮬레이션
  })
}

const goBack = () => {
  router.go(-1)
}
</script>

<style scoped>
.product-list {
  padding: 20px;
  background-color: #f0f0f0;
  min-height: 100vh;
}

.header {
  display: flex;
  align-items: center;
  margin-bottom: 20px;
}

.back-button {
  background-color: #4CAF50;
  border: none;
  color: white;
  padding: 10px 20px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin-right: 20px;
  cursor: pointer;
  border-radius: 5px;
}

.title {
  font-size: 24px;
  color: #333;
  margin: 0;
}

.product-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
  gap: 20px;
}

.product-item {
  background-color: white;
  border-radius: 10px;
  overflow: hidden;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
  cursor: pointer;
  transition: transform 0.3s ease;
}

.product-item:hover {
  transform: translateY(-5px);
}

.product-content {
  padding: 20px;
}

.product-name {
  font-size: 20px;
  color: #333;
  margin-bottom: 10px;
}

.product-description {
  font-size: 14px;
  color: #666;
  margin-bottom: 15px;
}

.product-price {
  font-size: 18px;
  font-weight: bold;
  color: #4CAF50;
  margin-bottom: 10px;
}

.product-duration {
  font-size: 14px;
  color: #888;
}

.error-message, .loading-message {
  text-align: center;
  font-size: 18px;
  color: #333;
  margin-top: 20px;
}

.error-message {
  color: #f44336;
}

.payment-popup {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.5);
  display: flex;
  justify-content: center;
  align-items: center;
}

.payment-content {
  background-color: white;
  padding: 20px;
  border-radius: 10px;
  text-align: center;
}

.payment-content button {
  margin: 10px;
  padding: 10px 20px;
  background-color: #4CAF50;
  color: white;
  border: none;
  border-radius: 5px;
  cursor: pointer;
}

.payment-content button:hover {
  background-color: #45a049;
}
</style>
